config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end 
  root "extras#home"  
  resources :services
  get '/bookingvehicle' => 'bookings#bookingvehicle'
  get 'home' => 'extras#home'
  get 'faq' => 'extras#faq'
  get 'our_team' => 'extras#our_team'
  get 'about_us' => 'extras#about_us'
  get 'contact_us' => 'extras#contact_us'
  get 'tnc' => 'extras#tnc'
  get 'privacy_policy' => 'extras#privacy_policy'
  get 'admin' => 'members#admin'
get '/bookingvehicle' => 'bookings#bookingvehicle'

get '/servicecost' => 'services#servicecost'

  get 'adminshow' => 'members#adminshow'
  resources :messages
  resources :prelandings
  resources :brands
  resources :models
  resources :variants
  resources :vehicles
  resources :uservehicles
  resources :userroles
  resources :bookings
  resources :members
  resources :vehicle_services
  # map.check_email "registrations/check_email", :controller => "registrations", :action => "check_email"
  # map.resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booked_service.rb
class BookedService < ApplicationRecord
  belongs_to :booking
  belongs_to :service
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :uservehicle
  belongs_to :user
  belongs_to :service  

  def uservehicle
  Uservehicle.unscoped { super }
	end

	def service
  Service.unscoped { super }
	end
	
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :models, dependent: :destroy
	has_many :vehicles, dependent: :destroy
	has_many :uservehicles, dependent: :destroy
	validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :brand
  validates :name, presence: true, uniqueness: true
end

app/models/prelanding.rb
class Prelanding < ApplicationRecord
	validates :email, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	acts_as_paranoid
	 has_attached_file :photo, :styles =>{:thumb => "40x40>" ,  :small => "250x250#", :large => "500x360>", :xlarge => "1000x500>" }
	 validates_attachment :photo,presence: true, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	 has_many :vehicle_services

	 has_many :vehicles, through: :vehicle_services
	 has_many :bookings

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,:omniauth_providers => [:facebook]
    has_many :uservehicles , dependent: :destroy
    has_many :bookings
    belongs_to :userrole
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,4})\z/i

	validates :name, format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/,
    flash: "Only allows letters" }
	has_attached_file :image, :styles => { :small => "90x90>" ,:thumb => "30x30>" ,:medium => "220x200>"},
                            :default_url => 'default.jpg'
                    
	validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  def self.from_omniauth(auth)

  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    user.image = auth.info.image
  user.save!

  end
end

def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new(session["devise.user_attributes"], without_protection: true) do |user|
      user.attributes = params
      user.valid?
    end
  else
    super
  end
end
def password_required?
  super && provider.blank?
end
  
  def update_without_password(params, *options)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/models/userrole.rb
class Userrole < ApplicationRecord
	has_many :users
end

app/models/uservehicle.rb
class Uservehicle < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  has_many :bookings
  belongs_to :vehicle
  belongs_to :brand
  validates :reg_no, presence: true, uniqueness: true
  validates :manf_year, presence: true
  

   def uservehicle_name
    "#{vehicle.brand.name} #{vehicle.model.name} #{vehicle.variant.name}  (#{reg_no}) "
  end

end

app/models/variant.rb
class Variant < ApplicationRecord
has_many :vehicles 
	validates :name, presence: true, uniqueness: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :brand
  belongs_to :model
  belongs_to :variant
  has_many :uservehicles ,dependent: :destroy
  has_many :vehicle_services
  accepts_nested_attributes_for :vehicle_services, allow_destroy: true
  has_many :services, through: :vehicle_services
  def vehicle_name
    "#{brand.name} #{model.name} #{variant.name}"
  end
end

app/models/vehicle_service.rb
class VehicleService < ApplicationRecord
  belongs_to :vehicle ,optional: true
  belongs_to :service ,optional: true
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

	def index
		@services= Service.all
	end

	def new
		@service = Service.new
		authorize @service
	end
	def show
		@service = Service.find(params[:id])
		@b=VehicleService.where(service_id: @service.id)
		authorize @service
	end
	def edit
		@service = Service.find(params[:id])
		authorize @service
	end

	def create
		@service = Service.new(service_params)
		@service.save
	    redirect_to service_path(@service)
	    flash.notice = 'Service was successfully created'
	end

	def update
		@service = Service.find(params[:id])
		@service.update(service_params)
		redirect_to service_path(@service)
		flash.notice = 'Service was successfully created'
	end

	def servicecost
		@ab = VehicleService.where(:service_id=>params[:service_id],:vehicle_id=>params[:vehicle_id]).first.basic_cost
		respond_to do |format|
			format.js
	    end
	end

	private

	def service_params
		params.require(:service).permit(:name,:description ,:photo ,:required ,:covered)
	end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/services/_form.html.erb
<style type="text/css">
  .form-control{
  border: 1px solid black !important;
  border-radius: 6px !important;
    height: auto!important;
   padding: 8px 12px !important;
}
.input-group {
    -webkit-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
    -moz-box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
    box-shadow: 0px 2px 5px 0px rgba(0,0,0,0.21)!important;
}
.btn{
      box-shadow: 3px 3px 1px 0px rgba(0, 0, 0, 0.26);
    }

</style>
<div class="panel-body" >
<%= form_for @service , :html => { :multipart => true, class: "form-horizontal" ,:id => "new_service"} do |f| %>
 <div class="form-group required">
  
   <%= f.label "Name of Service", class: "control-label col-md-5 col-xs-12 col-sm-5 text-center requiredField"%>
      <div class="controls col-md-3 col-xs-12 col-sm-5 "> 
           <%= f.text_field :name, autofocus: true, required: :true,class: "input-md textinput textInput form-control m-b-10"%>   
                       </div> 
  </div>
  <div class="form-group required">
  
   <%= f.label "Description", class: "control-label col-md-5 col-xs-12 col-sm-5 text-center requiredField"%>
      <div class="controls col-md-3 col-xs-12 col-sm-5 "> 
           <%= f.text_area :description, required: :true,class: "input-md textinput textInput form-control m-b-10"%>   
                       </div> 
  </div>
  <div class="form-group required">
  
   <%= f.label "When is it required?", class: "control-label col-md-5 col-xs-12 col-sm-5 text-center requiredField"%>
      <div class="controls col-md-3 col-xs-12 col-sm-5 "> 
           <%= f.text_area :required, required: :true, class: "input-md textinput textInput form-control m-b-10"%>   
                       </div> 
  </div>
  <div class="form-group required">
  
   <%= f.label "What all is covered?", class: "control-label col-md-5 col-xs-12 col-sm-5 text-center requiredField"%>
      <div class="controls col-md-3 col-xs-12 col-sm-5 "> 
           <%= f.text_area :covered, required: :true, class: "input-md textinput textInput form-control m-b-10"%>   
                       </div> 
  </div>
  
<div class="form-group ">
  
   <%= f.label "Image", class: "control-label col-md-5 col-xs-12 col-sm-5 text-center "%>
<div class="fileinput fileinput-new" data-provides="fileinput">
                                                    <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 250px; height: 200px; border: 1px solid #e3e3e3;">
                                                   <%if @service.photo.exists?%>
                                                  <%= image_tag @service.photo.url(:large) %>
                                                   <%end%>
                                               </div>
                 
                                                <div>
                                                 <span class="btn btn-default btn-file">
                                                  <span class="fileinput-new">Select image</span>
                                                   <span class="fileinput-exists">Change</span>
                                                    <%if @service.photo.exists?%>
                                                         <%= f.file_field :photo %>
                                              
                                                      <%else%>
                                                        <%= f.file_field :photo %>
                                                      <%end%>
                                                       </span>
                                                <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Remove</a>
                                             </div>

</div>

  </div>

                                             </div>
                                            

   <div class="form-group">
                          <div class="controls col-md-12 col-md-offset-3 text-center">
                             <%= f.submit 'Submit', class: "btn btn-primary btn btn-info m-b-40" %>  
                          </div>
                    </div>

   
</div>

<% end %>

<script type="text/javascript">
$(document).ready(function () {
$("#new_service").validate({
rules: {
"service[name]": {required: true},
"service[description]": {required: true},
"service[required]": {required: true},
"service[covered]": {required: true}
}
});
});
</script>

app/views/services/edit.html.erb
<div class="container-fluid">
		<h3 class="serviceunder">Edit A Service
		</h3>
<%= render 'form'%>
</div>

app/views/services/index.html.erb
<style type="text/css">
	.img-responsive{
		width: 100%;
		height: 100%;
	}
	.card .context {
    position: absolute;
    bottom: 0;
    left: 0;
    right: 0;
    color: #fff;
    padding: 12px 16px;
    background-color: rgba(0, 0, 0, 0.5);
}

</style>
<div class="clearfix bg-service media-padding">

    <div class="col-md-12 col-xs-12 col-sm-12 col-lg-12 text-center color-orange">
        <h2 class=" m-t-50 m-b-50">OUR SERVICES</h2>
    </div>
  <div class="col-xs-12 col-sm-12 col-lg-12 col-md-12">
   <% Service.all.each do |services|%>
    <div class="col-md-3 col-sm-6 col-lg-3 col-xs-12 parent-element">
       <div class="card card-deep-purple card-image bg-image ">
         <%= link_to (image_tag services.photo.url(:large), height: '100%', width: '100%'),service_path(services), class: "img-responsive"%>
          <div class="context color-orange h-100" >
          <span class="text-title text-center element f-20"><%= link_to services.name, service_path(services)%></span>
          </div>
       </div>
     </div>
   <%end%>
  </div>
</div>

app/views/services/new.html.erb
<div class="container-fluid">
		<h3 class="serviceunder">Add A Service
		</h3>
<%= render 'form'%>
</div>

app/views/services/servicecost.js.erb
$("#cost").empty()
$("#cost").append('Rs <%=@ab%>')

app/views/services/show.html.erb
<style type="text/css">
  .color-black:active{
    font-weight: 700;
    color: #f13c20;
  }
  a:hover{
    color: #f13c20;
  }
  .box{
    box-shadow: 1px 1px 17px rgba(0, 0, 0, 0.15);
    margin-bottom: 26px;
  }
  .button-vehicle:hover{
  background-color: #f13c20;
   border:2px solid white;
   color: white;
}
.button-vehicle1:hover{
  background-color: #f13c20;
   border:2px solid white;
   color: white;
}
.card .card-body {
    position: relative;
    padding: 20px 15px;
    text-align: left;
}
</style>



<div class="clearfix">

       <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 p-50 ">
           <div class="f-20 " style="margin-bottom: 20px;"><b><%= @service.name%></b>
             <span style="float: right;" class="hidden-xs hidden-sm">
               <%if user_signed_in?%>
                  <span ><%= link_to 'Book Now', new_booking_path ,:class => "button-vehicle2 p-dif " %></span>
                  <%else%>
                  <span ><a href="/#section-link" class = "button-vehicle2  p-dif">Book Now</a></span>
               <%end%>
               <button type="button" class="button-vehicle2 " data-toggle="modal" data-target="#myModal">Check out price</button>
             </span>
           </div>
           <hr>
           <div class="visible-xs visible-sm m-b-20">
              <%if user_signed_in?%>
                 <span ><%= link_to 'Book Now', new_booking_path ,:class => "button-vehicle2 media-p1 p-dif" %></span>
              <%else%>
                 <span ><a href="/#section-link" class = "button-vehicle2 media-p1 p-dif ">Book Now</a></span>
              <%end%>
              <button type="button" class="button-vehicle2 media-p " data-toggle="modal" data-target="#myModal">Check out price</button>

           </div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6"><%= image_tag @service.photo.url(:large) ,:class => "img-responsive box border"%></div>
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6">
        <div class="m-t-20"><b><u>Description:</u></b><p><%= @service.description%></p></div>
        <div class="m-t-20"><b><u>When it is required?</u></b><p><%= @service.required%></p></div>
        <div class="m-t-20"><b><u>What all is covered?</u></b><p><%= @service.covered%></p></div>
        </div>  
       </div>
</div>


<script type="text/javascript">

var service = "<%=@service.id%>";
function f5(){
        $.ajax({type: "GET",url: "/servicecost",data: {
        vehicle_id: $("#vehicle_vehicle_id option:selected").val(),service_id: service}
        });  
}
</script>

<!-- Modal -->
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Price Details</h4>
        </div>
        <div class="modal-body">
        <p class="color-orange">Select vehicle for cost</p>
           <div class="collection border-drop"><%= collection_select(:vehicle, :vehicle_id, @service.vehicles, :id, :vehicle_name ,{ :style => 'width: 100%;border: 1px solid;'},{ :onChange => "f5()"} ) %>
              </div>
              <br>
              <p id="cost" ></p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
      
    </div>
  </div>