config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'
  match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all

  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}
  devise_scope :user do
  	get '/users/sign_out' => 'devise/sessions#destroy'
  end 
  root "extras#home"  
  resources :services
  get '/bookingvehicle' => 'bookings#bookingvehicle'
  get 'home' => 'extras#home'
  get 'faq' => 'extras#faq'
  get 'our_team' => 'extras#our_team'
  get 'about_us' => 'extras#about_us'
  get 'contact_us' => 'extras#contact_us'
  get 'tnc' => 'extras#tnc'
  get 'privacy_policy' => 'extras#privacy_policy'
  get 'admin' => 'members#admin'
get '/bookingvehicle' => 'bookings#bookingvehicle'

get '/servicecost' => 'services#servicecost'

  get 'adminshow' => 'members#adminshow'
  resources :messages
  resources :prelandings
  resources :brands
  resources :models
  resources :variants
  resources :vehicles
  resources :uservehicles
  resources :userroles
  resources :bookings
  resources :members
  resources :vehicle_services
  # map.check_email "registrations/check_email", :controller => "registrations", :action => "check_email"
  # map.resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booked_service.rb
class BookedService < ApplicationRecord
  belongs_to :booking
  belongs_to :service
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :uservehicle
  belongs_to :user
  belongs_to :service  

  def uservehicle
  Uservehicle.unscoped { super }
	end

	def service
  Service.unscoped { super }
	end
	
end

app/models/brand.rb
class Brand < ApplicationRecord
	has_many :models, dependent: :destroy
	has_many :vehicles, dependent: :destroy
	has_many :uservehicles, dependent: :destroy
	validates :name, presence: true, uniqueness: true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/models/model.rb
class Model < ApplicationRecord
  belongs_to :brand
  validates :name, presence: true, uniqueness: true
end

app/models/prelanding.rb
class Prelanding < ApplicationRecord
	validates :email, presence: true
end

app/models/service.rb
class Service < ApplicationRecord
	acts_as_paranoid
	 has_attached_file :photo, :styles =>{:thumb => "40x40>" ,  :small => "250x250#", :large => "500x360>", :xlarge => "1000x500>" }
	 validates_attachment :photo,presence: true, content_type: { content_type: ["image/jpeg", "image/gif", "image/png"] }
	 has_many :vehicle_services

	 has_many :vehicles, through: :vehicle_services
	 has_many :bookings

end

app/models/user.rb
class User < ApplicationRecord
  acts_as_paranoid
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable,:omniauth_providers => [:facebook]
    has_many :uservehicles , dependent: :destroy
    has_many :bookings
    belongs_to :userrole
    validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,4})\z/i

	validates :name, format: { with: /\A[^0-9`!@#\$%\^&*+_=]+\z/,
    flash: "Only allows letters" }
	has_attached_file :image, :styles => { :small => "90x90>" ,:thumb => "30x30>" ,:medium => "220x200>"},
                            :default_url => 'default.jpg'
                    
	validates_attachment_size :image, :less_than => 5.megabytes
	validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']

  def self.from_omniauth(auth)

  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.provider = auth.provider
    user.uid = auth.uid
    user.name = auth.info.name
    user.email = auth.info.email
    user.image = auth.info.image
  user.save!

  end
end

def self.new_with_session(params, session)
  if session["devise.user_attributes"]
    new(session["devise.user_attributes"], without_protection: true) do |user|
      user.attributes = params
      user.valid?
    end
  else
    super
  end
end
def password_required?
  super && provider.blank?
end
  
  def update_without_password(params, *options)

    if params[:password].blank?
      params.delete(:password)
      params.delete(:password_confirmation) if params[:password_confirmation].blank?
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end
end

app/models/userrole.rb
class Userrole < ApplicationRecord
	has_many :users
end

app/models/uservehicle.rb
class Uservehicle < ApplicationRecord
  acts_as_paranoid
  belongs_to :user
  has_many :bookings
  belongs_to :vehicle
  belongs_to :brand
  validates :reg_no, presence: true, uniqueness: true
  validates :manf_year, presence: true
  

   def uservehicle_name
    "#{vehicle.brand.name} #{vehicle.model.name} #{vehicle.variant.name}  (#{reg_no}) "
  end

end

app/models/variant.rb
class Variant < ApplicationRecord
has_many :vehicles 
	validates :name, presence: true, uniqueness: true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :brand
  belongs_to :model
  belongs_to :variant
  has_many :uservehicles ,dependent: :destroy
  has_many :vehicle_services
  accepts_nested_attributes_for :vehicle_services, allow_destroy: true
  has_many :services, through: :vehicle_services
  def vehicle_name
    "#{brand.name} #{model.name} #{variant.name}"
  end
end

app/models/vehicle_service.rb
class VehicleService < ApplicationRecord
  belongs_to :vehicle ,optional: true
  belongs_to :service ,optional: true
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
	def new
		@vehicle = Vehicle.new
		@vehicle.vehicle_services.build
		@brand= Brand.new
		@brands= Brand.all
		@service= Service.all
		@model=Model.new
		@models=Brand.order(:id)
		@variant=Variant.new
		@variants=Variant.all
		authorize @vehicle

	end
	def show
		@vehicle = Vehicle.find(params[:id])
	end
	def edit
		@vehicle = Vehicle.find(params[:id])
		@brand= Brand.new
		@brands= Brand.all
		@model=Model.new
		@models=Brand.order(:id)
		@variant=Variant.new
		@variants=Variant.all
		authorize @vehicle
	end

	def create
		@vehicle = Vehicle.new(vehicle_params)
		@vehicle.save
		@memeber=current_user
	    redirect_to vehicle_path(@vehicle)
	    flash.notice = 'Vehicle was successfully created'
	end

	def update
		@vehicle = Vehicle.find(params[:id])
		@vehicle.update(vehicle_params)
		@memeber=current_user
	    redirect_to vehicle_path(@vehicle)
		flash.notice = 'Vehicle was successfully created'
	end
	def destroy
		@vehicle = Vehicle.find(params[:id])
		@vehicle.destroy
		respond_to do |format|
			format.html { redirect_to root_url, notice: 'Vehicle was successfully deleted.' }
		end
	end
	private

	def vehicle_params
		params.require(:vehicle).permit(:startyear, :brand_id, :model_id, :variant_id ,:vehicle_services_attributes => [:id,:service_id,:vehicle_id,:basic_cost,:_destroy])
	end

end

		

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/extras_helper.rb
module ExtrasHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_cost.html.erb
<%= form_for (@cost) do |f| %>
                
	<p>
		<%= f.text_field :cost ,:placeholder=>""%>
	</p>
	<p>
		<%=f.submit%>
	</p>
<%end%>


                   

app/views/vehicles/_form.html1.erb
  <div class="container">             
    <div id="signupbox" style=" margin-top:50px" class="mainbox col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-2">
      <div class="panel panel-info">

           <div class="panel-title text-center " style="  border-bottom: 2px solid #f13c20;
  width: 151px;
  text-align: center;
  margin-right: auto;
  margin-left: auto;">Add A Vehicle

           </div>
       
    
        <div class="panel-body" >
        <%= form_for @vehicle, html: {class: "form-horizontal"},remote: true do |f| %>
          <div id="brandbox" class="form-group required">
          <%= f.label "Brand",class: "control-label col-md-3 requiredField" ,:style => "margin-top: 18px;"%><br> 
            <div class="controls col-md-6 ">
            <%= f.collection_select :brand_id, @brands, :id, :name,{prompt: 'Select Brand'},{class: "input-md emailinput form-control"}%>
              </div>
              <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Brand", '#new_brand_modal', 'data-toggle' => 'modal', class: "modalinks"%>
            </div>
           </div>
              
          <div id="modelbox" class="form-group required">
          <%= f.label "Model", class: "control-label col-md-3 requiredField"%>
            <div class="controls col-md-6 ">
           <%= f.grouped_collection_select :model_id, @models, :models, :name, :id, :name, {prompt: 'Select Model'},{class: "input-md  textinput textInput form-control"}%>
               </div>
              <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Model", '#new_model_modal', 'data-toggle' => 'modal',class: "modalinks"%>
          </div>
        </div>
          <div id="variantbox" class="form-group required">
          <%= f.label "Variant",class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 ">
            <%= f.collection_select :variant_id, @variants, :id, :name ,{prompt: 'Select Variant'},{class: "input-md emailinput form-control"}%>
             </div> 
              <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Variant", '#new_variant_modal', 'data-toggle' => 'modal',class: "modalinks"%>
              </div>
               
          </div>
          <%unless @vehicle.new_record?%>
          <div  class="form-group required">
          <%= f.label :Services ,class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 "> 
            <%= hidden_field_tag "vehicle[service_ids][]", nil%>
                <%Service.all.each do |service|%>
                  <%= check_box_tag "vehicle[service_ids][]" ,service.id, @vehicle.service_ids.include?(service.id), id: dom_id(service) %>
                  <%=label_tag dom_id(service),service.name %><br>

                <%end%>        
             </div>

              <%=f.fields_for :vehicle_services do |builder|%>
                <fieldset>
                <%#=builder.label :basic_cost,"Cost"%>
                <%= builder.text_field :basic_cost,:placeholder=>"Cost"%>
                </fieldset>
                <%end%>        
          </div>

          </div>
          <%end%>
          <div  class="form-group required">
          <%= f.label :startyear,class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 "> 
            <%= f.text_field :startyear, required: :true,class: "input-md textinput textInput form-control m-b-10"%>    
             </div>
          </div>
          <div class="form-group">
              <div class="controls col-md-4 col-md-offset-4 text-center">
              <%= f.submit 'Submit', class: "btn btn-primary btn btn-info" %>  
              </div>
          </div>    
        </div>
      </div>
    </div> 
  </div>


<% end %>

<div class="modal fade" id="new_brand_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new brand</h4>
      </div>
      <div class="modal-body">
        <%= render 'brands/form', modal: true %>
      </div>
     
    </div>
  </div>
</div>

<div class="modal fade" id="new_model_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new model</h4>
      </div>
      <div class="modal-body">
        <%= render 'models/form', modal: true %>
      </div>
   
    </div>
  </div>
</div>

<div class="modal fade" id="new_variant_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new variant</h4>
      </div>
      <div class="modal-body">
        <%= render 'variants/form', modal: true %>
      </div>
      
    </div>
  </div>
</div>

<script type="text/javascript">
jQuery(function() {
 var models = $('#vehicle_model_id').html();
 return $('#vehicle_brand_id').change(function() {
  var brand = $('#vehicle_brand_id :selected').text();
   var options = $(models).filter(`optgroup[label='${brand}']`).html();
  if (options) {
   return $('#vehicle_model_id').html(options);
  } else {
   return $('#vehicle_model_id').empty();
 }
 });
});
$("#vehicle_brand_id").change(function () {
   if ($("#vehicle_brand_id").val() == 0) {
     $('#vehicle_model_id').attr('disabled', 'disabled');
     } else {
       $('#vehicle_model_id').removeAttr('disabled');
     }
}).trigger("change");

$(document).ready(function () {
$("#new_vehicle").validate({
rules: {
"vehicle[brand_id]": {required: true},
"vehicle[model_id]": {required: true},
"vehicle[variant_id]": {required: true},
"vehicle[startyear]": {required: true}
}
});
});
$(function(){
  $(' input[type=checkbox]').click(function(){
    $(this).parent('form').submit();
    alert('sda');
  });

});

</script>

   

app/views/vehicles/_form1.html.erb
<style type="text/css">
  label.error{
   top: 23px;
    z-index: 9;
    position: absolute;
    color: #ce0000;
    font-size: 11px;
    right: 15px;} 
}
</style>
      <div class="panel panel-info">
  <div class="panel-body" >
  <%= form_for @vehicle, html: {class: "form-horizontal"},remote: true do |f| %>
    <div id="brandbox" class="form-group required">
    <%= f.label "Brand",class: "control-label col-md-3 requiredField" ,:style => "margin-top: 18px;"%><br> 
      <div class="controls col-md-6 ">
      <%= f.collection_select :brand_id, @brands, :id, :name,{prompt: 'Select Brand'},{class: "input-md emailinput form-control"}%>
      </div>
        <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Brand", '#new_brand_modal', 'data-toggle' => 'modal', class: "modalinks"%>
        </div>
      </div>  

      <div id="modelbox" class="form-group required">
      <%= f.label "Model", class: "control-label col-md-3 requiredField"%>
        <div class="controls col-md-6 ">
        <%= f.grouped_collection_select :model_id, @models, :models, :name, :id, :name, {prompt: 'Select Model'},{class: "input-md  textinput textInput form-control"}%>
        </div>
          <div id="variantbox" class="form-group required">
          <%= f.label "Variant",class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 ">
            <%= f.collection_select :variant_id, @variants, :id, :name ,{prompt: 'Select Variant'},{class: "input-md emailinput form-control"}%>
             </div> 
              <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Variant", '#new_variant_modal', 'data-toggle' => 'modal',class: "modalinks"%>
              </div>
               
          </div>
          <%#unless @vehicle.new_record?%>
          <div  class="form-group required">
          <%= f.label :Services ,class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 "> 
            <%#= hidden_field_tag "vehicle[service_id][]", nil%>
                <%Service.all.each do |service|%>
                  <%= check_box_tag "vehicle[service_id][]" ,service.id, @vehicle.service_ids.include?(service.id), id: dom_id(service) %>
                  <%=label_tag dom_id(service),service.name %><br>

                <%end%>        
             </div>

              <%=f.fields_for :vehicle_services do |builder|%>
                <fieldset>
                <%#=builder.label :basic_cost,"Cost"%>
                <%= builder.text_field :basic_cost,:placeholder=>"Cost"%>
                </fieldset>
                <%end%>        
          </div>

          </div>
          <%#end%>
          <div  class="form-group required">
          <%= f.label :startyear,class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 "> 
            <%= f.text_field :startyear, required: :true,class: "input-md textinput textInput form-control m-b-10"%>    
             </div>
          </div>
          <div class="form-group">
              <div class="controls col-md-4 col-md-offset-4 text-center">
              <%= f.submit 'Submit', class: "btn btn-primary btn btn-info" %>  
              </div>
          </div>    
        </div>
      </div>
      
      </div>

<% end %>
<div class="modal fade" id="new_brand_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new brand</h4>
      </div>
      <div class="modal-body">
        <%= render 'brands/form', modal: true %>
      </div>
     
    </div>
  </div>
</div>

<div class="modal fade" id="new_model_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new model</h4>
      </div>
      <div class="modal-body">
        <%= render 'models/form', modal: true %>
      </div>
   
    </div>
  </div>
</div>

<div class="modal fade" id="new_variant_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new variant</h4>
      </div>
      <div class="modal-body">
        <%= render 'variants/form', modal: true %>
      </div>
      
    </div>
  </div>
</div>

<script type="text/javascript">
jQuery(function() {
 var models = $('#vehicle_model_id').html();
 return $('#vehicle_brand_id').change(function() {
  var brand = $('#vehicle_brand_id :selected').text();
   var options = $(models).filter(`optgroup[label='${brand}']`).html();
  if (options) {
   return $('#vehicle_model_id').html(options);
  } else {
   return $('#vehicle_model_id').empty();
 }
 });
});
$("#vehicle_brand_id").change(function () {
   if ($("#vehicle_brand_id").val() == 0) {
     $('#vehicle_model_id').attr('disabled', 'disabled');
     } else {
       $('#vehicle_model_id').removeAttr('disabled');
     }
}).trigger("change");

$(document).ready(function () {
$("#new_vehicle").validate({
rules: {
"vehicle[brand_id]": {required: true},
"vehicle[model_id]": {required: true},
"vehicle[variant_id]": {required: true},
"vehicle[startyear]": {required: true}
}
});
});
$(function(){
  $(' input[type=checkbox]').click(function(){
    $(this).parent('form').submit();
    alert('sda');
  });

});

</script>

   

app/views/vehicles/_variant.html.erb
<%# modal ||= false %>
<%# remote = modal ? true : false %>
<%#= form_for(@variant, remote: remote, html: {role: :form, 'data-model' => 'variant'}) do |f| %>

 <!--  <div class="field"> -->
    <%#= f.label :"Variant" %><!-- <br /> -->
    <%#= f.text_field :name, autofocus: true, required: :true %>
  <!-- </div> -->
 
<%# end %>

app/views/vehicles/_vehicleservices.html.erb
<li>
	<div><%= f.collection_select :service_id,Service.all,:id,:name ,{prompt: 'Select Service'},{class: "input-md emailinput form-control"} %></div>
	<br>
	<div><%= f.text_field :basic_cost,:placeholder=>"Cost" ,class: "input-md textinput textInput form-control m-b-10"%></div>
	<div><%= f.link_to_remove "Remove Service" ,class: "modalinks btn" %></div>
	<br>
</li>  

app/views/vehicles/costonedit.html.erb
<style type="text/css">
  label.error{
   top: 23px;
    z-index: 9;
    position: absolute;
    color: #ce0000;
    font-size: 11px;
    right: 15px;} 
}
</style>
      <div class="panel panel-info">
  <div class="panel-body" >
  <%= form_for @vehicle, html: {class: "form-horizontal"} do |f| %>
    <div id="brandbox" class="form-group required">
    <%= f.label "Brand",class: "control-label col-md-3 requiredField" ,:style => "margin-top: 18px;"%><br> 
      <div class="controls col-md-6 ">
      <%= f.collection_select :brand_id, @brands, :id, :name,{prompt: 'Select Brand'},{class: "input-md emailinput form-control"}%>
      </div>
        <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Brand", '#new_brand_modal', 'data-toggle' => 'modal', class: "modalinks"%>
        </div>
      </div>  

      <div id="modelbox" class="form-group required">
      <%= f.label "Model", class: "control-label col-md-3 requiredField"%>
        <div class="controls col-md-6 ">
        <%= f.grouped_collection_select :model_id, @models, :models, :name, :id, :name, {prompt: 'Select Model'},{class: "input-md  textinput textInput form-control"}%>
        </div>
        <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Model", '#new_model_modal', 'data-toggle' => 'modal',class: "modalinks"%>
        </div>
      </div>
      <div id="variantbox" class="form-group required">
      <%= f.label "Variant",class: "control-label col-md-3  requiredField" %>
        <div class="controls col-md-6 ">
        <%= f.collection_select :variant_id, @variants, :id, :name ,{prompt: 'Select Variant'},{class: "input-md emailinput form-control"}%>
        </div> 
        <div class="col-md-2 btn btn-default btnposition"><%= link_to "Add Variant", '#new_variant_modal', 'data-toggle' => 'modal',class: "modalinks"%>
        </div>
      </div>
      <%#unless @vehicle.new_record?%>
          <div  class="form-group required">
          <%= f.label :Services ,class: "control-label col-md-3  requiredField" %>
            <div class="controls col-md-6 "> 
            <%#= hidden_field_tag "vehicle[service_id][]", nil%>
                <%Service.all.each do |service|%>
                  <%= check_box_tag "vehicle[service_id][]" ,service.id, @vehicle.service_ids.include?(service.id), id: dom_id(service) %>
                  <%=label_tag dom_id(service),service.name %><br>

                <%end%>        
             </div>
              <%=f.fields_for :vehicle_services do |builder|%>
                <fieldset>
                <%#=builder.label :basic_cost,"Cost"%>
                <%= builder.text_field :basic_cost,:placeholder=>"Cost"%>
                </fieldset>
                <%end%>        

          </div>

          </div>
          <%#end%>
      <div  class="form-group required">
      <%= f.label :startyear,class: "control-label col-md-3  requiredField" %>
        <div class="controls col-md-6 "> 
        <%= f.text_field :startyear, required: :true,class: "input-md textinput textInput form-control m-b-10"%>    
        </div>
      </div>
      <div class="form-group">
        <div class="controls col-md-12 col-md-offset-3 text-center">
        <%= f.submit 'Submit', class: "btn btn-primary btn btn-info" %>  
        </div>
        </div>    
      </div>
      </div>

<% end %>
<div class="modal fade" id="new_brand_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new brand</h4>
      </div>
      <div class="modal-body">
        <%= render 'brands/form', modal: true %>
      </div>
     
    </div>
  </div>
</div>

<div class="modal fade" id="new_model_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new model</h4>
      </div>
      <div class="modal-body">
        <%= render 'models/form', modal: true %>
      </div>
   
    </div>
  </div>
</div>

<div class="modal fade" id="new_variant_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add new variant</h4>
      </div>
      <div class="modal-body">
        <%= render 'variants/form', modal: true %>
      </div>
      
    </div>
  </div>
</div>

<script type="text/javascript">
jQuery(function() {
 var models = $('#vehicle_model_id').html();
 return $('#vehicle_brand_id').change(function() {
  var brand = $('#vehicle_brand_id :selected').text();
   var options = $(models).filter(`optgroup[label='${brand}']`).html();
  if (options) {
   return $('#vehicle_model_id').html(options);
  } else {
   return $('#vehicle_model_id').empty();
 }
 });
});
$("#vehicle_brand_id").change(function () {
   if ($("#vehicle_brand_id").val() == 0) {
     $('#vehicle_model_id').attr('disabled', 'disabled');
     } else {
       $('#vehicle_model_id').removeAttr('disabled');
     }
}).trigger("change");

$(document).ready(function () {
$("#new_vehicle").validate({
rules: {
"vehicle[brand_id]": {required: true},
"vehicle[model_id]": {required: true},
"vehicle[variant_id]": {required: true}
// "vehicle[startyear]": {required: true}
}
});
});

</script>

   
<style type="text/css">
  label.error{
   top: 23px;
    z-index: 9;
    position: absolute;
    color: #ce0000;
    font-size: 11px;
    right: 15px;} 
}
</style>

app/views/vehicles/edit.html.erb
	<div class="container m-t-b-50">             
		<div id="signupbox" style=" margin-top:50px" class="mainbox col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-2">
			<h3  class="formunder">Vehicle
			</h3>
		<%=render 'form'%>
		</div>
	</div>

app/views/vehicles/new.html.erb
	<div class="container">             
		<div id="signupbox" style=" margin-top:50px" class="mainbox col-md-7 col-md-offset-2 col-sm-8 col-sm-offset-2">
			<h3  class="formunder">Add A Vehicle
			</h3>
		<%=render 'form'%>
		</div>
	</div>

	          